### ISSUE TITLE
报错了，大佬帮我看看怎么回事（已解决）

### ISSUE THREAD

**Issue by jem1997** [zhizhuoshuma/WechatBot#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\WechatBot-main\main.py", line 1, in <module>
    from servercli.server import *
  File "C:\Users\Administrator\Desktop\WechatBot-main\servercli\server.py", line 17, in <module>
    blacklist_room_id = config.get("server", "blacklist_room_id")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'blacklist_room_id' in section: 'server'

**Comment by kkx600** [comment]
代码更新，修复了几个bug，可以使用git fetch更新一下代码
