### ISSUE TITLE
请问注入后，安装完环境依赖，在没有修改config的情况下运行出现这个问题该怎么办？

### ISSUE THREAD

**Issue by momingxiaoyang** [zhizhuoshuma/WechatBot#16]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'y4tacker_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\codeProgram\wechatBot\WechatBot\main.py", line 5, in <module>
    from servercli.server import *
  File "D:\codeProgram\wechatBot\WechatBot\servercli\server.py", line 6, in <module>
    from httpcli.everyday_news import *
  File "D:\codeProgram\wechatBot\WechatBot\httpcli\everyday_news.py", line 22, in <module>
    y4tacker_url = config.get("apiService", "y4tacker_url")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'y4tacker_url' in section: 'apiService'

好像是配置文件中缺少 'apiService' 部分？

**Comment by kkx600** [comment]
删除相关的调用代码即可
